### Numpy Basics

In [10]:
python_list = [1, 2, 3, 4, 5]
print(python_list)

import numpy as np
numpy_array = np.array([1, 2, 3, 4, 5])
print(numpy_array)

print("\n1D Array")
ar1d = np.array([10,20, 30,40, 50])
print(ar1d)

print("\n2D Array")
ar2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(ar2d)

print("\n MultiDimensional Array or Matrix" )
matrix = np.array([[2,4,6],
                   [8,10,12]])
print(matrix)

print("\n Arrays with Default Zeros Values" )
zeros_array = np.zeros(3)
print(zeros_array)

print("\n Arrays with Default One's Values")
ones_array = np.ones((2,3))
print(ones_array)

print("\n Arrays with Default specific Values")
filled_array = np.full((2,3), 7)
print(filled_array)

print("\n Creating sequences of numbers in numpy")
sequence_arr = np.arange(1, 10, 2)
print(sequence_arr)

print("\n Creating identity matrics")
identity_matrix = np.eye(3)
print(identity_matrix)

[1, 2, 3, 4, 5]
[1 2 3 4 5]

1D Array
[10 20 30 40 50]

2D Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 MultiDimensional Array or Matrix
[[ 2  4  6]
 [ 8 10 12]]

 Arrays with Default Zeros Values
[0. 0. 0.]

 Arrays with Default One's Values
[[1. 1. 1.]
 [1. 1. 1.]]

 Arrays with Default specific Values
[[7 7 7]
 [7 7 7]]

 Creating sequences of numbers in numpy
[1 3 5 7 9]

 Creating identity matrics
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Numpy Array Properites and Operations

In [9]:
import numpy as np
# Array Checking Properties
arr_2d = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

# Array Shape
print("\nArray Shape")
print(arr_2d.shape)

# Array Size (Total No of Elements)
print("\nArray Size")
print(arr_2d.size)

# NDIM No. of Dimensions 1D, 2D, 3D
print("\nNo of Dimensions")
print(arr_2d.ndim)

# dtype Datatype of element
print("\nDatatype of element")
print(arr_2d.dtype)


Array Shape
(3, 4)

Array Size
12

No of Dimensions
2

Datatype of element
int64


In [13]:
import numpy as np
# Array changing properties

arr = np.array([1.2, 2.5, 3.8])

int_arr = arr.astype(int)
print("\nChanging Float Type to INT")
print(arr)
print(arr.dtype)
print("\nAfter Changing.....")
print(int_arr)
print(int_arr.dtype)


Changing Float Type to INT
[1.2 2.5 3.8]
float64

After Changing.....
[1 2 3]
int64


In [ ]:
import numpy as np
# Array Mathematical Operations

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(arr + 2)
print(arr * 2)
print(arr ** 2)

# Aggregation Function ( Summary )
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


### Indexing and Slicing Arrays

In [19]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(arr[0])
print(arr[2])
print(arr[-1])

# Slicing
print(arr[1:4])
print(len(arr))
print(arr[1:len(arr):2])
print(arr[::-1])

# Fancy Indexing
print(arr[[0, 2, 4]])

10
30
90
[20 30 40]
9
[20 40 60 80]
[90 80 70 60 50 40 30 20 10]
[10 30 50]


### Filtering in Numpy

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[arr > 25])
