### Numpy Basics

In [10]:
python_list = [1, 2, 3, 4, 5]
print(python_list)

import numpy as np
numpy_array = np.array([1, 2, 3, 4, 5])
print(numpy_array)

print("\n1D Array")
ar1d = np.array([10,20, 30,40, 50])
print(ar1d)

print("\n2D Array")
ar2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(ar2d)

print("\n MultiDimensional Array or Matrix" )
matrix = np.array([[2,4,6],
                   [8,10,12]])
print(matrix)

print("\n Arrays with Default Zeros Values" )
zeros_array = np.zeros(3)
print(zeros_array)

print("\n Arrays with Default One's Values")
ones_array = np.ones((2,3))
print(ones_array)

print("\n Arrays with Default specific Values")
filled_array = np.full((2,3), 7)
print(filled_array)

print("\n Creating sequences of numbers in numpy")
sequence_arr = np.arange(1, 10, 2)
print(sequence_arr)

print("\n Creating identity matrics")
identity_matrix = np.eye(3)
print(identity_matrix)

[1, 2, 3, 4, 5]
[1 2 3 4 5]

1D Array
[10 20 30 40 50]

2D Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 MultiDimensional Array or Matrix
[[ 2  4  6]
 [ 8 10 12]]

 Arrays with Default Zeros Values
[0. 0. 0.]

 Arrays with Default One's Values
[[1. 1. 1.]
 [1. 1. 1.]]

 Arrays with Default specific Values
[[7 7 7]
 [7 7 7]]

 Creating sequences of numbers in numpy
[1 3 5 7 9]

 Creating identity matrics
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Numpy Array Properites and Operations

In [9]:
import numpy as np
# Array Checking Properties
arr_2d = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

# Array Shape
print("\nArray Shape")
print(arr_2d.shape)

# Array Size (Total No of Elements)
print("\nArray Size")
print(arr_2d.size)

# NDIM No. of Dimensions 1D, 2D, 3D
print("\nNo of Dimensions")
print(arr_2d.ndim)

# dtype Datatype of element
print("\nDatatype of element")
print(arr_2d.dtype)


Array Shape
(3, 4)

Array Size
12

No of Dimensions
2

Datatype of element
int64


In [13]:
import numpy as np
# Array changing properties

arr = np.array([1.2, 2.5, 3.8])

int_arr = arr.astype(int)
print("\nChanging Float Type to INT")
print(arr)
print(arr.dtype)
print("\nAfter Changing.....")
print(int_arr)
print(int_arr.dtype)


Changing Float Type to INT
[1.2 2.5 3.8]
float64

After Changing.....
[1 2 3]
int64


In [ ]:
import numpy as np
# Array Mathematical Operations

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(arr + 2)
print(arr * 2)
print(arr ** 2)

# Aggregation Function ( Summary )
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


### Indexing and Slicing Arrays

In [19]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(arr[0])
print(arr[2])
print(arr[-1])

# Slicing
print(arr[1:4])
print(len(arr))
print(arr[1:len(arr):2])
print(arr[::-1])

# Fancy Indexing
print(arr[[0, 2, 4]])

10
30
90
[20 30 40]
9
[20 40 60 80]
[90 80 70 60 50 40 30 20 10]
[10 30 50]


### Filtering in Numpy

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[arr > 25])


[30 40 50 60]


### Reshaping of an Array

In [5]:
import numpy as np

# Reshaping an array allows you to change its dimensions without changing its data.
# Reshaping does not copy a new array, it just changes the view of the original array.

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print("\nReshaped Array:")
print(reshaped_arr)

# Flattening an array converts a multi-dimensional array into a one-dimensional array.
# .ravel() returns a view – modifying it may affect the original array.
# .flatten() returns a copy – modifying it does NOT affect the original array.

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

ravel_result = arr_2d.ravel()
flatten_result = arr_2d.flatten()

# Modify both results
ravel_result[0] = 100
flatten_result[1] = 200

print("\nAfter modifying ravel_result[0] = 100")
print("Flattened Array using ravel():")
print(ravel_result)

print("\nAfter modifying flatten_result[1] = 200")
print("Flattened Array using flatten():")
print(flatten_result)

# Show original array to see effect
print("\nOriginal 2D Array after modifications:")
print(arr_2d)



Reshaped Array:
[[1 2 3]
 [4 5 6]]

After modifying ravel_result[0] = 100
Flattened Array using ravel():
[100   2   3   4   5   6]

After modifying flatten_result[1] = 200
Flattened Array using flatten():
[  1 200   3   4   5   6]

Original 2D Array after modifications:
[[100   2   3]
 [  4   5   6]]


### Advanced Numpy

- Inserting In Array

In [ ]:
import numpy as np

"""
np.insert(array, index, value, axis=None)
array - original array
index - index at which value is to be inserted
value - value to be inserted
axis - None(default) for flattening the array in 1D,
if axis is specified, the value is inserted along that axis
axis = 0 , row wise
axis = 1 , column wise
"""

arr = np.array([10,20,30,40,50,60])
new_arr = np.insert(arr, 2, 100, axis=None)

print("\n Before Insertion:")
print(arr)

print("\n After Insertion:")
print(new_arr)

arr_2d = np.array([[1, 2], [4, 5]])

#insert a ne row
new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=0)

print("\nBefore Insertion in 2D Array:")
print(arr_2d)

print("\nAfter Insertion in 2D Array:")
print(new_arr_2d)


 Before Insertion:
[10 20 30 40 50 60]

 After Insertion:
[ 10  20 100  30  40  50  60]

Before Insertion in 2D Array:
[[1 2]
 [4 5]]

After Insertion in 2D Array:
[[1 2]
 [5 6]
 [4 5]]


- appending in Array

In [13]:
import numpy as np

arr = np.array([10,20,30])
new_arr = np.append(arr, [40, 50])

print("\nBefore Appending:")
print(arr)

print("\nAfter Appending:")
print(new_arr)


Before Appending:
[10 20 30]

After Appending:
[10 20 30 40 50]


- concatenating an Array

In [14]:
import numpy as np
 
"""
np.concatenate((array1, array2), axis=0)
axis 0 is for row-wise concatenation or vertical stacking
axis 1 is for column-wise concatenation or horizontal stacking
"""

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenated Array:")
print(new_arr)



Concatenated Array:
[1 2 3 4 5 6]


- removing elements from an array

In [18]:
import numpy as np

"""
np.delete(array, index, axis=None)
"""

arr = np.array([10, 20, 30, 40, 50, 60])
new_arr = np.delete(arr, 2, axis=None)

print("\nArray before Deletion:")
print(arr)

print("\nArray after Deletion:")
print(new_arr)

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_arr_2d = np.delete(arr_2d, 1, axis=0)

print("\n2D Array before Deletion:")
print(arr_2d)

print("\n2D Array after Deletion:")
print(new_arr_2d)


Array before Deletion:
[10 20 30 40 50 60]

Array after Deletion:
[10 20 40 50 60]

2D Array before Deletion:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2D Array after Deletion:
[[1 2 3]
 [7 8 9]]


- stacking in an array

In [19]:
import numpy as np

"""
vertically stacking
horizontally stacking

vstack() row wise
stack() column wise
"""

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("\nVertical Stacking:")
print(np.vstack((arr1, arr2)))

print("\nHorizontal Stacking:")
print(np.hstack((arr1, arr2)))


Vertical Stacking:
[[1 2 3]
 [4 5 6]]

Horizontal Stacking:
[1 2 3 4 5 6]


- Splitting in an Array

In [21]:
import numpy as np

"""
np.split()
splits an array into multiple sub-arrays 

np.hsplit()
horizontal split

np.vsplit()
vertical split  
"""

arr = np.array([10,20,30,40,50,60,70,80,90])

print(np.split(arr, 3))

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]


### Broadcasting
Broadcasting is a way that NumPy lets you do operations (like add, subtract, etc.) on arrays of different shapes as if they had the same shape.

In [27]:
import numpy as np

prices = [100, 200, 300]
discount = 10
final_prices = []

for price in prices:
    final_price = price - (price * discount / 100)
    final_prices.append(final_price)

print("\nFinal Prices after Discount:")
print(final_prices)


prices = np.array([100,200,300,400])
discount = 10
final_prices = prices - (prices * discount / 100)

print("\nFinal Prices after Discount using Broadcasting:")
print(final_prices)



Final Prices after Discount:
[90.0, 180.0, 270.0]

Final Prices after Discount using Broadcasting:
[ 90. 180. 270. 360.]


How numpy handle arrays of different shapes 
1. Matching Dimensions
```python
arr1 = [1,2,3]
arr2 = [4,5,6]

# After performing arr1 + arr2
result = [5, 7, 9]
```
2. Expanding single elements
```python
arr1 = [1,2,3]

# After performing arr1 + 10
result = [10, 20, 30]
```
3. Incompatible Shapes
```python
arr1 = [1, 2, 3]
arr2 = [1, 2]

# After performing arr1 + arr2
result = error
```

In [33]:
import numpy as np

arr = np.array([100, 200, 300])
result = arr * 2

print("\nOriginal Array:")
print(arr)

print("\nResult after Broadcasting:")
print(result)

# Broadcasting 1D array to 2D array

matrix = np.array([[1,2,3], [4,5,6]]) # 2 * 3 Matrix
vector = np.array([10, 20, 30]) # 1D Array

result = matrix + vector
print("\n1d to 2d Broadcasting Result:")
print(result)



Original Array:
[100 200 300]

Result after Broadcasting:
[200 400 600]

1d to 2d Broadcasting Result:
[[11 22 33]
 [14 25 36]]


### Vectorization
Vectorization means performing operations on entire arrays (vectors) instead of using loops to process individual elements.

In [36]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2
print("\nResult of Vectorized Addition:")
print(result)

arr3 = np.array([10, 20, 30])
result = arr3 * 3
print("\nResult of Vectorized Multiplication:")
print(result)



Result of Vectorized Addition:
[5 7 9]

Result of Vectorized Multiplication:
[30 60 90]


### TL;DR:
- Vectorization = use arrays instead of loops to perform operations.
- Broadcasting = automatic shape matching of arrays to perform operations.

## Handling Missing Values
Builtin Functions
- np.isnan -- detects missing value
- np.nan_to_num() -- replace NaN with an specific num
- np.isinf() -- to detect infinite values

In [8]:
import numpy as np

arr = np.array([1, 2, np.nan, 4, np.nan, 6])
print("\nDetect NaN:")
print(np.isnan(arr))

cleaned_arr = np.nan_to_num(arr, nan = 100)
print("\nReplace NaN with 100")
print(cleaned_arr)

arr1 = np.array([1, 2, np.inf, 4, -np.inf, 6])
print("\nDetect infinity:")
print(np.isinf(arr1))

cleaned_arr = np.nan_to_num(arr, posinf=1000, neginf=-1000)
print("\nReplace posinf with 1000 and neginf with -1000: ")
print(cleaned_arr)


Detect NaN:
[False False  True False  True False]

Replace NaN with 100
[  1.   2. 100.   4. 100.   6.]

Detect infinity:
[False False  True False  True False]

Replace posinf with 1000 and neginf with -1000: 
[1. 2. 0. 4. 0. 6.]
